### ISSUE TITLE
assignments: assignment 2 has a merge conflict scar

### ISSUE THREAD

**Issue by kortschak** [UofABioinformaticsHub/Biotech7005#27]
The [Assignment2.md](https://raw.githubusercontent.com/UofABioinformaticsHub/Biotech7005/master/Assignments/Assignment2.md) file has a merge conflict scar committed. Introduced in 8cb6c2674b5859909f62903fb214533e7c7c2c19.

/cc @steveped

**Comment by steveped** [comment]
Yeah. I thought I'd dealt with that. Maybe that was just locally. I've pushed it now
