### ISSUE TITLE
practical 1: topic 1 contains a question about trim_ws, which is not mentioned in the material

### ISSUE THREAD

**Issue by ArriWang** [UofABioinformaticsHub/Biotech7005#35]
![screen shot 2018-07-26 at 1 49 33 am](https://user-images.githubusercontent.com/41697827/43213910-eb3c148c-9076-11e8-92d6-28c07bc1c7eb.png)
Hi, 

In practical material topic 1, under the heading "Understanding read_csv()", in the last line, there is a question asking about "what do you think the argument trim_ws does?" 
This argument trim_ws is not mentioned previously or covered in the topic 1.

**Comment by kortschak** [comment]
Thank you for filing the issue. Do you think that this would be fixed adequately by changing the wording of that sentence to "The `read_csv` function can take an argument `trim_ws`. What do you think the `trim_ws` argument does?"

**Comment by kortschak** [comment]
Changing this is fine. I'll post an announcement linking to this though.

**Comment by steveped** [comment]
No problems. I actually misread this as a problem with the assignment so I can't see any real dramas with updating this. I've just pushed the change.
