### ISSUE TITLE
The Assignment Coversheet & meaning of the function "position" not clear in topic 3

### ISSUE THREAD

**Issue by ArriWang** [UofABioinformaticsHub/Biotech7005#36]
Hi, 

Could we get an announcement or email once the coversheet problem is fixed? As our first assignment is due on this Friday 3 August.  

Also, in topic 3 - plotting data, the "Combining with dplyr" section, the text mentioned "position = "dodge"", but it did not included in the code chunk. It would be more clear if include it within the code chunk, so we can know where it should be; or explain why we do not need to include it within the code in this situation. 
![screen shot 2018-07-31 at 9 37 30 pm](https://user-images.githubusercontent.com/41697827/43458911-0292ff40-950b-11e8-9d0f-7c9784b3d27b.png)

**Comment by kortschak** [comment]
@ArriWang The coversheet was added today and is available from [this page](https://uofabioinformaticshub.github.io/Biotech7005/COVERSHEET.html). Just copy the monospaced text into the correct location in the Rmd file you are submitting. I will post an announcement.

@steveped Would you look into the other part of this issue?

**Comment by ArriWang** [comment]
Thanks for your help : )

**Comment by steveped** [comment]
I've removed this line from the text.

**Comment by kortschak** [comment]
Thanks
