### ISSUE TITLE
Week 6 Practical

### ISSUE THREAD

**Issue by WhitevonGardner** [UofABioinformaticsHub/Biotech7005#38]
Demultiplexing
When we installed the sabre, we use the code:
conda remove sabre
cd /opt
sudo wget https://github.com/najoshi/sabre/archive/master.zip
sudo unzip master.zip
**sudo mv master sabre**
cd sabre
sudo make
cd /usr/local/bin
sudo ln -s /opt/sabre/sabre ./sabre

The 5th line has problem:
sudo mv master sabre

it should be:
sudo mv sabre-master sabre

Since when we unzip the file "master.zip", it gives us the folder named as "sabre-master" in vm

**Comment by steveped** [comment]
Thanks. I've resolved this now.
