### ISSUE TITLE
NGS Practical 2 code errors

### ISSUE THREAD

**Issue by vuongtoan2810** [UofABioinformaticsHub/Biotech7005#39]
I think one of the code in NGS Practical 2 has something wrong with it, I couldn't run the code 'bwa mem -t 2 ~/NGS_Practical/Celegans_chrI SRR2003569_sub_1.fastq.gz SRR2003569_sub_2.fastq.gz' because the program kept saying something like 'No such file/directory'. Please help.

**Comment by jimmybgammyknee** [comment]
Hi @vuongtoan2810, have you checked the directories of both "~/NGS_Practical/" and you current directory? If you do a list command on each you should see if you have those files in each directory.

`ls -l ~/NGS_Practical/
ls -l ./`

Note: File and directory names are case-sensitive, so check to see if you have exactly the same case spelling in each file and directory
