### ISSUE TITLE
Issue in Transcriptomics Practical : R loading featureCount output issue

### ISSUE THREAD

**Issue by Luan-Zhong** [UofABioinformaticsHub/Biotech7005#40]
# Issue Description
There is an issue to load the data in R for Transcriptomics Practical if you use your own featureCount result. There are four solutions to solve this problem.  

# Solutions

## 1. Download the output from the link provided in Practical

Run the following code in R

`cd ~/RNA_Practical`
`wget https://uofabioinformaticshub.github.io/Biotech7005/Practicals/Transcriptome_Practical/counts.out`

The code is to download the `counts.out` file to ~/RNA_Practical.

## 2. If you want to use your `featureCount` output result. 
There are three ways can load your counts.out correctly.

### (1) Move the output to ~/RNA_Practical in VM

`cd ~/RNA_Practical/02_aligned/counts`
`mv counts.out ~/RNA_Practical`

### (2) Changing the input directory of variable `file` in R

`file <- file.path("02_aligned","counts","counts.out")`

### (3) Editing the `countAlignments.sh` script

Editing the output directory as following
`COUNTDIR=~/RNA_Practical`

**Comment by steveped** [comment]
Thanks Luan. We may add this next time
