### ISSUE TITLE
A issue in RNAseq practical 

### ISSUE THREAD

**Issue by HangweiXi** [UofABioinformaticsHub/Biotech7005#42]
In the script: 
#!/bin/bash
FQDIR=~/RNA_Practical/01_rawData/fastq
SAMDIR=~/RNA_Practical/02_aligned/sam
LOGDIR=~/RNA_Practical/02_aligned/logs
BAMDIR=~/RNA_Practical/02_aligned/bam
IDX=~/genomes/Hsapiens/Homo_sapiens.GRCh38.dna.chromosome.1

for f in ${FQDIR}/*gz
  do
    echo -e "Running alignment on ${f}"
    SAM=${SAMDIR}/$(basename ${f} _1.fq.gz).sam
    BAM=${BAMDIR}/$(basename ${f} _1.fq.gz).sorted.bam
    hisat2 --known-splicesite-infile **${z10_splicesites}** \
    -x ${IDX} \
    -p 3 \
    -U ${f} \
    -S ${SAM} &> ${LOGDIR}/$(basename ${f} _1.fq.gz).log
    echo -e "done"
    echo "Converting ${SAM} to ${BAM}"
    samtools view -bh ${SAM} | samtools sort -o ${BAM}
    rm ${SAM}
  done

There should be an assignment for the  ${z10_splicesites}, 
such as FQDIR=~/RNA_Practical/01_rawData/fastq. But there is no assignment for z10_splicesites

**Comment by steveped** [comment]
Thanks. This has now been changed
