### ISSUE TITLE
can't find the coversheet

### ISSUE THREAD

**Issue by Sicong-liu** [UofABioinformaticsHub/Biotech7005#44]
The web link at the home page for assignment cover-sheet shows 404. the address might be wrong.

**Comment by kortschak** [comment]
The link at the home page is https://uofabioinformaticshub.github.io/Biotech7005/COVERSHEET.html. This works for me.

**Comment by kortschak** [comment]
The page that has that link is not part of this repository. I have fixed it as much as I can.

**Comment by steveped** [comment]
Hi. I also found the cover sheet at https://sciences.adelaide.edu.au/sites/default/files/docs/form-assessment-cover-sheet.docx
